[build]
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

# Для скачивания файлов
[[headers]]
  for = "/downloads/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Disposition = "attachment"